#!/usr/bin/bash

#
# script to start up LinkedIn with a query 
# (if you have Firefox installed)
# 

search=''
first=1

if [ "$#" -eq "0" ] 
then
	set echo; firefox https://linkedin.com 2>/dev/null &
else
	for i in "$@"
	do
		if [ $first -eq '1' ] 
		then
			search=$i
			first=0
		else 
			search=$search"+AND+$i"
		fi
	done
	set echo;  firefox https://www.linkedin.com/search/results/index/?keywords=$search 2>/dev/null &
fi
